apiVersion: v1
kind: Service
metadata:
  name: {{ include "delta-txn-service.fullname" . }}
  labels:
    {{- include "delta-txn-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "delta-txn-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
